/* Autogenerated file. Do not edit manually. */

/* eslint-disable max-classes-per-file */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable @typescript-eslint/consistent-type-imports */

/*
  Fuels version: 0.98.0
*/

import { Contract, Interface } from "fuels";
import type {
  Provider,
  Account,
  StorageSlot,
  Address,
  BigNumberish,
  BN,
  Bytes,
  FunctionFragment,
  InvokeFunction,
  StdString,
  StrSlice,
} from "fuels";

import type { Option, Enum } from "./common";

export enum AccessErrorInput {
  NotOwner = "NotOwner",
}
export enum AccessErrorOutput {
  NotOwner = "NotOwner",
}
export type IdentityInput = Enum<{
  Address: AddressInput;
  ContractId: ContractIdInput;
}>;
export type IdentityOutput = Enum<{
  Address: AddressOutput;
  ContractId: ContractIdOutput;
}>;
export enum InitializationErrorInput {
  CannotReinitialized = "CannotReinitialized",
}
export enum InitializationErrorOutput {
  CannotReinitialized = "CannotReinitialized",
}
export type StateInput = Enum<{
  Uninitialized: undefined;
  Initialized: IdentityInput;
  Revoked: undefined;
}>;
export type StateOutput = Enum<{
  Uninitialized: void;
  Initialized: IdentityOutput;
  Revoked: void;
}>;

export type AddressInput = { bits: string };
export type AddressOutput = AddressInput;
export type AssetIdInput = { bits: string };
export type AssetIdOutput = AssetIdInput;
export type AssetsSwappedInput = {
  pool_asset: AssetIdInput;
  is_buy: boolean;
  asset_in_amount: BigNumberish;
  asset_out_amount: BigNumberish;
};
export type AssetsSwappedOutput = {
  pool_asset: AssetIdOutput;
  is_buy: boolean;
  asset_in_amount: BN;
  asset_out_amount: BN;
};
export type AssetsWithdrawnInput = {
  asset_id: AssetIdInput;
  asset_amount: BigNumberish;
  eth_amount: BigNumberish;
};

export type ContractConfigInput = {
  fee_receiver: IdentityInput;
  fee_percent: BigNumberish;
  virtual_eth_reserves_init: BigNumberish;
  asset_reserves_init: BigNumberish;
  asset_decimals: BigNumberish;
  remain_asset_reserves: BigNumberish;
};
export type ContractConfigOutput = {
  fee_receiver: IdentityOutput;
  fee_percent: BN;
  virtual_eth_reserves_init: BN;
  asset_reserves_init: BN;
  asset_decimals: number;
  remain_asset_reserves: BN;
};
export type ContractIdInput = { bits: string };
export type ContractIdOutput = ContractIdInput;
export type FeeChargedInput = {
  pool_asset: AssetIdInput;
  eth_fee_percent: BigNumberish;
  eth_fee_amount: BigNumberish;
};
export type FeeChargedOutput = {
  pool_asset: AssetIdOutput;
  eth_fee_percent: BN;
  eth_fee_amount: BN;
};
export type OwnershipSetInput = { new_owner: IdentityInput };
export type OwnershipSetOutput = { new_owner: IdentityOutput };
export type PoolStateInput = {
  asset: AssetIdInput;
  is_completed: boolean;
  real_eth_reserves: BigNumberish;
  asset_reserves: BigNumberish;
  virtual_eth_reserves: BigNumberish;
  remain_asset_reserves: BigNumberish;
};
export type PoolStateOutput = {
  asset: AssetIdOutput;
  is_completed: boolean;
  real_eth_reserves: BN;
  asset_reserves: BN;
  virtual_eth_reserves: BN;
  remain_asset_reserves: BN;
};
export type PoolStateUpdatedInput = {
  asset: AssetIdInput;
  is_completed: boolean;
  real_eth_reserves: BigNumberish;
  asset_reserves: BigNumberish;
  virtual_eth_reserves: BigNumberish;
};
export type PoolStateUpdatedOutput = {
  asset: AssetIdOutput;
  is_completed: boolean;
  real_eth_reserves: BN;
  asset_reserves: BN;
  virtual_eth_reserves: BN;
};
export type PreviewResultUsingInputInput = {
  asset_id_out: AssetIdInput;
  amount_out: BigNumberish;
  sufficient_reserves: boolean;
};
export type PreviewResultUsingInputOutput = {
  asset_id_out: AssetIdOutput;
  amount_out: BN;
  sufficient_reserves: boolean;
};
export type PreviewResultUsingOutputInput = {
  asset_id_in: AssetIdInput;
  amount_in: BigNumberish;
  sufficient_reserves: boolean;
};
export type PreviewResultUsingOutputOutput = {
  asset_id_in: AssetIdOutput;
  amount_in: BN;
  sufficient_reserves: boolean;
};
export type PreviewResultVirtualUsingInputInput = {
  amount_out: BigNumberish;
  sufficient_reserves: boolean;
};
export type PreviewResultVirtualUsingInputOutput = {
  amount_out: BN;
  sufficient_reserves: boolean;
};
export type PreviewResultVirtualUsingOutputInput = {
  amount_in: BigNumberish;
  sufficient_reserves: boolean;
};
export type PreviewResultVirtualUsingOutputOutput = {
  amount_in: BN;
  sufficient_reserves: boolean;
};

const abi = {
  programType: "contract",
  specVersion: "1",
  encodingVersion: "1",
  concreteTypes: [

    {
      type: "()",
      concreteTypeId:
        "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d",
    },
    {
      type: "(u64, struct std::asset_id::AssetId)",
      concreteTypeId:
        "e10d8bfc338a29565debd72645b365f9b0481e462fd7d591848de4a73223d58d",
      metadataTypeId: 0,
    },
    {
      type: "enum standards::src5::AccessError",
      concreteTypeId:
        "3f702ea3351c9c1ece2b84048006c8034a24cbc2bad2e740d0412b4172951d3d",
      metadataTypeId: 3,
    },
    {
      type: "enum standards::src5::State",
      concreteTypeId:
        "192bc7098e2fe60635a9918afb563e4e5419d386da2bdbf0d716b4bc8549802c",
      metadataTypeId: 4,
    },
    {
      type: "enum std::identity::Identity",
      concreteTypeId:
        "ab7cd04e05be58e3fc15d424c2c4a57f824a2a2d97d67252440a3925ebdc1335",
      metadataTypeId: 5,
    },
    {
      type: "enum std::option::Option<struct interface::PoolState>",
      concreteTypeId:
        "2b7de9cbc7ae3bb51b1db952b886d863d45ae61ac164666cc67d478f15689f2d",
      metadataTypeId: 6,
      typeArguments: [
        "7ed2d2bc036be719c83491cb401a35c9ffe40e88331a8ba267e3c4e0ff112df3",
      ],
    },
    {
      type: "enum std::option::Option<u64>",
      concreteTypeId:
        "d852149004cc9ec0bbe7dc4e37bffea1d41469b759512b6136f2e865a4c06e7d",
      metadataTypeId: 6,
      typeArguments: [
        "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0",
      ],
    },
    {
      type: "enum sway_libs::ownership::errors::InitializationError",
      concreteTypeId:
        "1dfe7feadc1d9667a4351761230f948744068a090fe91b1bc6763a90ed5d3893",
      metadataTypeId: 7,
    },
    {
      type: "str",
      concreteTypeId:
        "8c25cb3686462e9a86d2883c5688a22fe738b0bbc85f458d2d2b5f3f667c6d5a",
    },
    {
      type: "struct events::AssetsSwapped",
      concreteTypeId:
        "effaeddb6e1aaf210b5339b6021cb61019e209d7ff5805f879b1e04f7ca47f38",
      metadataTypeId: 10,
    },
    {
      type: "struct events::AssetsWithdrawn",
      concreteTypeId:
        "f3d5131d9943cfcd4cf63157044e0f940b976338516e5f77d6516bb67dd0ede8",
      metadataTypeId: 11,
    },
    {
      type: "struct events::FeeCharged",
      concreteTypeId:
        "ffb5799f54ad1837c4ee9199a388fdf1c0fe4ae2f212ff098ab31000c2481fc0",
      metadataTypeId: 12,

    },
    {
      type: "struct events::PoolStateUpdated",
      concreteTypeId:
        "d3af19714c381e3973bb62ad5d6034ae3c64d8c69f9d552942d06894dce9c7ea",

      metadataTypeId: 13,

    },
    {
      type: "struct interface::ContractConfig",
      concreteTypeId:
        "a68382ac816e4071ab8245c99af3f3f0cf607d6d21a98b0d872ee319a5ed6a63",

      metadataTypeId: 14,

    },
    {
      type: "struct interface::PoolState",
      concreteTypeId:
        "7ed2d2bc036be719c83491cb401a35c9ffe40e88331a8ba267e3c4e0ff112df3",

      metadataTypeId: 15,

    },
    {
      type: "struct interface::PreviewResultUsingInput",
      concreteTypeId:
        "2a7dc121dd6165796ff026f47011bdfd719a9f72132d07de575aeb55ce825aee",

      metadataTypeId: 16,

    },
    {
      type: "struct interface::PreviewResultUsingOutput",
      concreteTypeId:
        "f52f83cc4cec5736ae5baf0ae38b860c4f850477ab3d230293919bde7b14db33",

      metadataTypeId: 17,

    },
    {
      type: "struct interface::PreviewResultVirtualUsingInput",
      concreteTypeId:
        "d009db241bb0ae560633fc5a0b51e37c5495c43b0ed8f0b8528c44583825e2b0",

      metadataTypeId: 18,

    },
    {
      type: "struct interface::PreviewResultVirtualUsingOutput",
      concreteTypeId:
        "ba945a748e63afba2eff7c7df86534fc28b54b33d65889bfd509a54bb941b440",

      metadataTypeId: 19,

    },
    {
      type: "struct std::asset_id::AssetId",
      concreteTypeId:
        "c0710b6731b1dd59799cf6bef33eee3b3b04a2e40e80a0724090215bbf2ca974",

      metadataTypeId: 21,

    },
    {
      type: "struct std::string::String",
      concreteTypeId:
        "9a7f1d3e963c10e0a4ea70a8e20a4813d1dc5682e28f74cb102ae50d32f7f98c",

      metadataTypeId: 25,

    },
    {
      type: "struct sway_libs::ownership::events::OwnershipSet",
      concreteTypeId:
        "e1ef35033ea9d2956f17c3292dea4a46ce7d61fdf37bbebe03b7b965073f43b5",

      metadataTypeId: 26,

    },
    {
      type: "u64",
      concreteTypeId:
        "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0",
    },
  ],
  metadataTypes: [
    {
      type: "(_, _)",
      metadataTypeId: 0,
      components: [
        {
          name: "__tuple_element",
          typeId:
            "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0",
        },
        {
          name: "__tuple_element",

          typeId: 21,

        },
      ],
    },
    {
      type: "b256",
      metadataTypeId: 1,
    },
    {
      type: "bool",
      metadataTypeId: 2,
    },
    {
      type: "enum standards::src5::AccessError",
      metadataTypeId: 3,
      components: [
        {
          name: "NotOwner",
          typeId:
            "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d",
        },
      ],
    },
    {
      type: "enum standards::src5::State",
      metadataTypeId: 4,
      components: [
        {
          name: "Uninitialized",
          typeId:
            "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d",
        },
        {
          name: "Initialized",
          typeId: 5,
        },
        {
          name: "Revoked",
          typeId:
            "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d",
        },
      ],
    },
    {
      type: "enum std::identity::Identity",
      metadataTypeId: 5,
      components: [
        {
          name: "Address",

          typeId: 20,
        },
        {
          name: "ContractId",
          typeId: 24,

        },
      ],
    },
    {
      type: "enum std::option::Option",
      metadataTypeId: 6,
      components: [
        {
          name: "None",
          typeId:
            "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d",
        },
        {
          name: "Some",
          typeId: 8,
        },
      ],
      typeParameters: [8],
    },
    {
      type: "enum sway_libs::ownership::errors::InitializationError",
      metadataTypeId: 7,
      components: [
        {
          name: "CannotReinitialized",
          typeId:
            "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d",
        },
      ],
    },
    {
      type: "generic T",
      metadataTypeId: 8,
    },
    {
      type: "raw untyped ptr",
      metadataTypeId: 9,

    },
    {
      type: "struct events::AssetsSwapped",
      metadataTypeId: 10,
      components: [
        {
          name: "pool_asset",
          typeId: 21,
        },
        {
          name: "is_buy",
          typeId: 2,
        },
        {
          name: "asset_in_amount",
          typeId:
            "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0",
        },
        {
          name: "asset_out_amount",
          typeId:
            "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0",
        },
      ],
    },
    {
      type: "struct events::AssetsWithdrawn",
      metadataTypeId: 11,
      components: [
        {
          name: "asset_id",
          typeId: 21,
        },
        {
          name: "asset_amount",
          typeId:
            "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0",
        },
        {
          name: "eth_amount",
          typeId:
            "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0",
        },
      ],
    },
    {
      type: "struct events::FeeCharged",
      metadataTypeId: 12,
      components: [
        {
          name: "pool_asset",
          typeId: 21,
        },
        {
          name: "eth_fee_percent",

          typeId:
            "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0",
        },
        {

          name: "eth_fee_amount",

          typeId:
            "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0",
        },
      ],
    },
    {
      type: "struct events::PoolStateUpdated",

      metadataTypeId: 13,
      components: [
        {
          name: "asset",
          typeId: 21,

        },
        {
          name: "is_completed",
          typeId: 2,
        },
        {
          name: "real_eth_reserves",
          typeId:
            "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0",
        },
        {
          name: "asset_reserves",
          typeId:
            "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0",
        },
        {
          name: "virtual_eth_reserves",
          typeId:
            "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0",
        },
      ],
    },
    {
      type: "struct interface::ContractConfig",

      metadataTypeId: 14,

      components: [
        {
          name: "fee_receiver",
          typeId: 5,
        },
        {
          name: "fee_percent",
          typeId:
            "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0",
        },
        {
          name: "virtual_eth_reserves_init",
          typeId:
            "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0",
        },
        {
          name: "asset_reserves_init",
          typeId:
            "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0",
        },
        {
          name: "asset_decimals",

          typeId: 27,

        },
        {
          name: "remain_asset_reserves",
          typeId:
            "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0",
        },
      ],
    },
    {
      type: "struct interface::PoolState",

      metadataTypeId: 15,
      components: [
        {
          name: "asset",
          typeId: 21,

        },
        {
          name: "is_completed",
          typeId: 2,
        },
        {
          name: "real_eth_reserves",
          typeId:
            "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0",
        },
        {
          name: "asset_reserves",
          typeId:
            "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0",
        },
        {
          name: "virtual_eth_reserves",
          typeId:
            "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0",
        },
        {
          name: "remain_asset_reserves",
          typeId:
            "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0",
        },
      ],
    },
    {
      type: "struct interface::PreviewResultUsingInput",

      metadataTypeId: 16,
      components: [
        {
          name: "asset_id_out",
          typeId: 21,

        },
        {
          name: "amount_out",
          typeId:
            "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0",
        },
        {
          name: "sufficient_reserves",
          typeId: 2,
        },
      ],
    },
    {
      type: "struct interface::PreviewResultUsingOutput",

      metadataTypeId: 17,
      components: [
        {
          name: "asset_id_in",
          typeId: 21,

        },
        {
          name: "amount_in",
          typeId:
            "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0",
        },
        {
          name: "sufficient_reserves",
          typeId: 2,
        },
      ],
    },
    {
      type: "struct interface::PreviewResultVirtualUsingInput",

      metadataTypeId: 18,

      components: [
        {
          name: "amount_out",
          typeId:
            "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0",
        },
        {
          name: "sufficient_reserves",
          typeId: 2,
        },
      ],
    },
    {
      type: "struct interface::PreviewResultVirtualUsingOutput",

      metadataTypeId: 19,

      components: [
        {
          name: "amount_in",
          typeId:
            "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0",
        },
        {
          name: "sufficient_reserves",
          typeId: 2,
        },
      ],
    },
    {
      type: "struct std::address::Address",

      metadataTypeId: 20,

      components: [
        {
          name: "bits",
          typeId: 1,
        },
      ],
    },
    {
      type: "struct std::asset_id::AssetId",

      metadataTypeId: 21,

      components: [
        {
          name: "bits",
          typeId: 1,
        },
      ],
    },
    {
      type: "struct std::bytes::Bytes",

      metadataTypeId: 22,
      components: [
        {
          name: "buf",
          typeId: 23,

        },
        {
          name: "len",
          typeId:
            "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0",
        },
      ],
    },
    {
      type: "struct std::bytes::RawBytes",

      metadataTypeId: 23,

      components: [
        {
          name: "ptr",
          typeId: 9,
        },
        {
          name: "cap",
          typeId:
            "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0",
        },
      ],
    },
    {
      type: "struct std::contract_id::ContractId",
      metadataTypeId: 24,

      components: [
        {
          name: "bits",
          typeId: 1,
        },
      ],
    },
    {
      type: "struct std::string::String",
      metadataTypeId: 25,
      components: [
        {
          name: "bytes",
          typeId: 22,

        },
      ],
    },
    {
      type: "struct sway_libs::ownership::events::OwnershipSet",
      metadataTypeId: 26,

      components: [
        {
          name: "new_owner",
          typeId: 5,
        },
      ],
    },
    {
      type: "u8",
      metadataTypeId: 27,

    },
  ],
  functions: [
    {
      inputs: [],
      name: "owner",
      output:
        "192bc7098e2fe60635a9918afb563e4e5419d386da2bdbf0d716b4bc8549802c",
      attributes: [
        {
          name: "storage",
          arguments: ["read"],
        },
      ],
    },
    {
      inputs: [
        {
          name: "pool_asset",
          concreteTypeId:
            "c0710b6731b1dd59799cf6bef33eee3b3b04a2e40e80a0724090215bbf2ca974",
        },
        {
          name: "min_output",
          concreteTypeId:
            "d852149004cc9ec0bbe7dc4e37bffea1d41469b759512b6136f2e865a4c06e7d",
        },
        {
          name: "deadline",
          concreteTypeId:
            "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0",
        },
      ],
      name: "buy_exact_input",
      output:
        "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0",
      attributes: [
        {
          name: "payable",
          arguments: [],
        },
        {
          name: "storage",
          arguments: ["read", "write"],
        },
      ],
    },
    {
      inputs: [
        {
          name: "pool_asset",
          concreteTypeId:
            "c0710b6731b1dd59799cf6bef33eee3b3b04a2e40e80a0724090215bbf2ca974",
        },
        {
          name: "output",
          concreteTypeId:
            "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0",
        },
        {
          name: "deadline",
          concreteTypeId:
            "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0",
        },
      ],
      name: "buy_exact_output",
      output:
        "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0",
      attributes: [
        {
          name: "payable",
          arguments: [],
        },
        {
          name: "storage",
          arguments: ["read", "write"],
        },
      ],
    },
    {
      inputs: [
        {
          name: "name",
          concreteTypeId:
            "9a7f1d3e963c10e0a4ea70a8e20a4813d1dc5682e28f74cb102ae50d32f7f98c",
        },
        {
          name: "symbol",
          concreteTypeId:
            "9a7f1d3e963c10e0a4ea70a8e20a4813d1dc5682e28f74cb102ae50d32f7f98c",
        },
        {
          name: "uri",
          concreteTypeId:
            "9a7f1d3e963c10e0a4ea70a8e20a4813d1dc5682e28f74cb102ae50d32f7f98c",
        },
      ],
      name: "create_asset_with_pool_buy_exact_input",
      output:
        "e10d8bfc338a29565debd72645b365f9b0481e462fd7d591848de4a73223d58d",
      attributes: [
        {
          name: "payable",
          arguments: [],
        },
        {
          name: "storage",
          arguments: ["read", "write"],
        },
      ],
    },
    {
      inputs: [
        {
          name: "name",
          concreteTypeId:
            "9a7f1d3e963c10e0a4ea70a8e20a4813d1dc5682e28f74cb102ae50d32f7f98c",
        },
        {
          name: "symbol",
          concreteTypeId:
            "9a7f1d3e963c10e0a4ea70a8e20a4813d1dc5682e28f74cb102ae50d32f7f98c",
        },
        {
          name: "uri",
          concreteTypeId:
            "9a7f1d3e963c10e0a4ea70a8e20a4813d1dc5682e28f74cb102ae50d32f7f98c",
        },
        {
          name: "output",
          concreteTypeId:
            "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0",
        },
      ],
      name: "create_asset_with_pool_buy_exact_output",
      output:
        "e10d8bfc338a29565debd72645b365f9b0481e462fd7d591848de4a73223d58d",
      attributes: [
        {
          name: "payable",
          arguments: [],
        },
        {
          name: "storage",
          arguments: ["read", "write"],
        },
      ],
    },
    {
      inputs: [
        {
          name: "name",
          concreteTypeId:
            "9a7f1d3e963c10e0a4ea70a8e20a4813d1dc5682e28f74cb102ae50d32f7f98c",
        },
        {
          name: "symbol",
          concreteTypeId:
            "9a7f1d3e963c10e0a4ea70a8e20a4813d1dc5682e28f74cb102ae50d32f7f98c",
        },
        {
          name: "uri",
          concreteTypeId:
            "9a7f1d3e963c10e0a4ea70a8e20a4813d1dc5682e28f74cb102ae50d32f7f98c",
        },
      ],
      name: "create_asset_with_pool_empty",
      output:
        "c0710b6731b1dd59799cf6bef33eee3b3b04a2e40e80a0724090215bbf2ca974",
      attributes: [
        {
          name: "storage",
          arguments: ["read", "write"],
        },
      ],
    },
    {
      inputs: [],
      name: "get_config",
      output:
        "a68382ac816e4071ab8245c99af3f3f0cf607d6d21a98b0d872ee319a5ed6a63",
      attributes: [
        {
          name: "storage",
          arguments: ["read"],
        },
      ],
    },
    {
      inputs: [
        {
          name: "asset_id",
          concreteTypeId:
            "c0710b6731b1dd59799cf6bef33eee3b3b04a2e40e80a0724090215bbf2ca974",
        },
      ],
      name: "get_pool",
      output:
        "2b7de9cbc7ae3bb51b1db952b886d863d45ae61ac164666cc67d478f15689f2d",
      attributes: [
        {
          name: "storage",
          arguments: ["read"],
        },
      ],
    },
    {
      inputs: [
        {
          name: "owner",
          concreteTypeId:
            "ab7cd04e05be58e3fc15d424c2c4a57f824a2a2d97d67252440a3925ebdc1335",
        },
        {
          name: "cfg",
          concreteTypeId:
            "a68382ac816e4071ab8245c99af3f3f0cf607d6d21a98b0d872ee319a5ed6a63",
        },
      ],
      name: "initialize",
      output:
        "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d",
      attributes: [
        {
          name: "storage",
          arguments: ["write"],
        },
      ],
    },
    {
      inputs: [
        {
          name: "asset_creator",
          concreteTypeId:
            "ab7cd04e05be58e3fc15d424c2c4a57f824a2a2d97d67252440a3925ebdc1335",
        },
      ],
      name: "initialize_asset_creator",
      output:
        "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d",
      attributes: [
        {
          name: "storage",
          arguments: ["write"],
        },
      ],
    },
    {
      inputs: [
        {
          name: "pool_asset",
          concreteTypeId:
            "c0710b6731b1dd59799cf6bef33eee3b3b04a2e40e80a0724090215bbf2ca974",
        },
        {
          name: "eth_amount",
          concreteTypeId:
            "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0",
        },
      ],
      name: "preview_buy_exact_input",
      output:
        "2a7dc121dd6165796ff026f47011bdfd719a9f72132d07de575aeb55ce825aee",
      attributes: [
        {
          name: "storage",
          arguments: ["read"],
        },
      ],
    },
    {
      inputs: [
        {
          name: "eth_amount",
          concreteTypeId:
            "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0",
        },
      ],
      name: "preview_buy_exact_input_virtual",
      output:
        "d009db241bb0ae560633fc5a0b51e37c5495c43b0ed8f0b8528c44583825e2b0",
      attributes: [
        {
          name: "storage",
          arguments: ["read"],
        },
      ],
    },
    {
      inputs: [
        {
          name: "pool_asset",
          concreteTypeId:
            "c0710b6731b1dd59799cf6bef33eee3b3b04a2e40e80a0724090215bbf2ca974",
        },
        {
          name: "asset_amount",
          concreteTypeId:
            "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0",
        },
      ],
      name: "preview_buy_exact_output",
      output:
        "f52f83cc4cec5736ae5baf0ae38b860c4f850477ab3d230293919bde7b14db33",
      attributes: [
        {
          name: "storage",
          arguments: ["read"],
        },
      ],
    },
    {
      inputs: [
        {
          name: "asset_amount",
          concreteTypeId:
            "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0",
        },
      ],
      name: "preview_buy_exact_output_virtual",
      output:
        "ba945a748e63afba2eff7c7df86534fc28b54b33d65889bfd509a54bb941b440",
      attributes: [
        {
          name: "storage",
          arguments: ["read"],
        },
      ],
    },
    {
      inputs: [
        {
          name: "pool_asset",
          concreteTypeId:
            "c0710b6731b1dd59799cf6bef33eee3b3b04a2e40e80a0724090215bbf2ca974",
        },
        {
          name: "asset_amount",
          concreteTypeId:
            "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0",
        },
      ],
      name: "preview_sell_exact_input",
      output:
        "2a7dc121dd6165796ff026f47011bdfd719a9f72132d07de575aeb55ce825aee",
      attributes: [
        {
          name: "storage",
          arguments: ["read"],
        },
      ],
    },
    {
      inputs: [
        {
          name: "pool_asset",
          concreteTypeId:
            "c0710b6731b1dd59799cf6bef33eee3b3b04a2e40e80a0724090215bbf2ca974",
        },
        {
          name: "eth_amount",
          concreteTypeId:
            "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0",
        },
      ],
      name: "preview_sell_exact_output",
      output:
        "f52f83cc4cec5736ae5baf0ae38b860c4f850477ab3d230293919bde7b14db33",
      attributes: [
        {
          name: "storage",
          arguments: ["read"],
        },
      ],
    },
    {
      inputs: [
        {
          name: "pool_asset",
          concreteTypeId:
            "c0710b6731b1dd59799cf6bef33eee3b3b04a2e40e80a0724090215bbf2ca974",
        },
        {
          name: "min_output",
          concreteTypeId:
            "d852149004cc9ec0bbe7dc4e37bffea1d41469b759512b6136f2e865a4c06e7d",
        },
        {
          name: "deadline",
          concreteTypeId:
            "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0",
        },
      ],
      name: "sell_exact_input",
      output:
        "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0",
      attributes: [
        {
          name: "payable",
          arguments: [],
        },
        {
          name: "storage",
          arguments: ["read", "write"],
        },
      ],
    },
    {
      inputs: [
        {
          name: "pool_asset",
          concreteTypeId:
            "c0710b6731b1dd59799cf6bef33eee3b3b04a2e40e80a0724090215bbf2ca974",
        },
        {
          name: "output",
          concreteTypeId:
            "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0",
        },
        {
          name: "deadline",
          concreteTypeId:
            "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0",
        },
      ],
      name: "sell_exact_output",
      output:
        "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0",
      attributes: [
        {
          name: "payable",
          arguments: [],
        },
        {
          name: "storage",
          arguments: ["read", "write"],
        },
      ],
    },
    {
      inputs: [
        {
          name: "pool_asset",
          concreteTypeId:
            "c0710b6731b1dd59799cf6bef33eee3b3b04a2e40e80a0724090215bbf2ca974",

        },
      ],
      name: "withdraw_assets_from_pool",
      output:
        "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d",
      attributes: [
        {
          name: "to",
          concreteTypeId:
            "ab7cd04e05be58e3fc15d424c2c4a57f824a2a2d97d67252440a3925ebdc1335",
        },
      ],
      name: "withdraw_assets_from_pool",
      output:
        "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d",
      attributes: [
        {
          name: "storage",
          arguments: ["read", "write"],
        },
      ],

    },
  ],
  loggedTypes: [
    {
      logId: "10098701174489624218",
      concreteTypeId:
        "8c25cb3686462e9a86d2883c5688a22fe738b0bbc85f458d2d2b5f3f667c6d5a",
    },
    {
      logId: "18425767175683643447",
      concreteTypeId:
        "ffb5799f54ad1837c4ee9199a388fdf1c0fe4ae2f212ff098ab31000c2481fc0",
    },
    {
      logId: "15253438437327904313",
      concreteTypeId:
        "d3af19714c381e3973bb62ad5d6034ae3c64d8c69f9d552942d06894dce9c7ea",
    },
    {
      logId: "17292395245943303969",
      concreteTypeId:
        "effaeddb6e1aaf210b5339b6021cb61019e209d7ff5805f879b1e04f7ca47f38",
    },
    {
      logId: "2161305517876418151",
      concreteTypeId:
        "1dfe7feadc1d9667a4351761230f948744068a090fe91b1bc6763a90ed5d3893",
    },
    {
      logId: "16280289466020123285",
      concreteTypeId:
        "e1ef35033ea9d2956f17c3292dea4a46ce7d61fdf37bbebe03b7b965073f43b5",
    },
    {

      logId: "4571204900286667806",
      concreteTypeId:
        "3f702ea3351c9c1ece2b84048006c8034a24cbc2bad2e740d0412b4172951d3d",
    },

    {
      logId: "17569970539102195661",
      concreteTypeId:
        "f3d5131d9943cfcd4cf63157044e0f940b976338516e5f77d6516bb67dd0ede8",
    },

  ],
  messagesTypes: [],
  configurables: [],
};

const storageSlots: StorageSlot[] = [
  {
    key: "4a85c26b85cd1ac73285aef6fa28d8adaa161639395a533f576358914e503aa0",
    value: "0000000000000000000000000000000000000000000000000000000000000000",
  },
  {
    key: "93cf4d8c41e1594593ba20b7d5520b7d8d0ae5bac979f7db85f218bb344fecd5",
    value: "0000000000000000000000000000000000000000000000000000000000000000",
  },
  {
    key: "93cf4d8c41e1594593ba20b7d5520b7d8d0ae5bac979f7db85f218bb344fecd6",
    value: "0000000000000000000000000000000000000000000000000000000000000000",
  },
  {
    key: "93cf4d8c41e1594593ba20b7d5520b7d8d0ae5bac979f7db85f218bb344fecd7",
    value: "0900000000000000000000000000000000000000000000000000000000000000",
  },
  {
    key: "9f34096532d037c7838cd48087852ca15a8fbe708d5fd716471c740dc57234fa",
    value: "0000000000000000000000000000000000000000000000000000000000000000",
  },
  {
    key: "9f34096532d037c7838cd48087852ca15a8fbe708d5fd716471c740dc57234fb",
    value: "0000000000000000000000000000000000000000000000000000000000000000",
  },
  {
    key: "f585ff0c202941490fbc396ca0c0f659a51e305aad97e25ed9245fcd8035a7c7",
    value: "f8f8b6283d7fa5b672b530cbb84fcccb4ff8dc40f8176ef4544ddb1f1952ad07",
  },

];

export class AmmInterface extends Interface {
  constructor() {
    super(abi);
  }

  declare functions: {
    owner: FunctionFragment;
    buy_exact_input: FunctionFragment;
    buy_exact_output: FunctionFragment;
    create_asset_with_pool_buy_exact_input: FunctionFragment;
    create_asset_with_pool_buy_exact_output: FunctionFragment;
    create_asset_with_pool_empty: FunctionFragment;
    get_config: FunctionFragment;
    get_pool: FunctionFragment;
    initialize: FunctionFragment;
    initialize_asset_creator: FunctionFragment;
    preview_buy_exact_input: FunctionFragment;
    preview_buy_exact_input_virtual: FunctionFragment;
    preview_buy_exact_output: FunctionFragment;
    preview_buy_exact_output_virtual: FunctionFragment;
    preview_sell_exact_input: FunctionFragment;
    preview_sell_exact_output: FunctionFragment;
    sell_exact_input: FunctionFragment;
    sell_exact_output: FunctionFragment;
    withdraw_assets_from_pool: FunctionFragment;
  };
}

export class Amm extends Contract {
  static readonly abi = abi;
  static readonly storageSlots = storageSlots;

  declare interface: AmmInterface;
  declare functions: {
    owner: InvokeFunction<[], StateOutput>;
    buy_exact_input: InvokeFunction<
      [
        pool_asset: AssetIdInput,
        min_output: Option<BigNumberish>,
        deadline: BigNumberish
      ],
      BN
    >;
    buy_exact_output: InvokeFunction<
      [pool_asset: AssetIdInput, output: BigNumberish, deadline: BigNumberish],
      BN
    >;
    create_asset_with_pool_buy_exact_input: InvokeFunction<
      [name: StdString, symbol: StdString, uri: StdString],
      [BN, AssetIdOutput]
    >;
    create_asset_with_pool_buy_exact_output: InvokeFunction<
      [
        name: StdString,
        symbol: StdString,
        uri: StdString,
        output: BigNumberish
      ],
      [BN, AssetIdOutput]
    >;
    create_asset_with_pool_empty: InvokeFunction<
      [name: StdString, symbol: StdString, uri: StdString],
      AssetIdOutput
    >;
    get_config: InvokeFunction<[], ContractConfigOutput>;
    get_pool: InvokeFunction<[asset_id: AssetIdInput], Option<PoolStateOutput>>;
    initialize: InvokeFunction<
      [owner: IdentityInput, cfg: ContractConfigInput],
      void
    >;
    initialize_asset_creator: InvokeFunction<
      [asset_creator: IdentityInput],
      void
    >;
    preview_buy_exact_input: InvokeFunction<
      [pool_asset: AssetIdInput, eth_amount: BigNumberish],
      PreviewResultUsingInputOutput
    >;
    preview_buy_exact_input_virtual: InvokeFunction<
      [eth_amount: BigNumberish],
      PreviewResultVirtualUsingInputOutput
    >;
    preview_buy_exact_output: InvokeFunction<
      [pool_asset: AssetIdInput, asset_amount: BigNumberish],
      PreviewResultUsingOutputOutput
    >;
    preview_buy_exact_output_virtual: InvokeFunction<
      [asset_amount: BigNumberish],
      PreviewResultVirtualUsingOutputOutput
    >;
    preview_sell_exact_input: InvokeFunction<
      [pool_asset: AssetIdInput, asset_amount: BigNumberish],
      PreviewResultUsingInputOutput
    >;
    preview_sell_exact_output: InvokeFunction<
      [pool_asset: AssetIdInput, eth_amount: BigNumberish],
      PreviewResultUsingOutputOutput
    >;
    sell_exact_input: InvokeFunction<
      [
        pool_asset: AssetIdInput,
        min_output: Option<BigNumberish>,
        deadline: BigNumberish
      ],
      BN
    >;
    sell_exact_output: InvokeFunction<
      [pool_asset: AssetIdInput, output: BigNumberish, deadline: BigNumberish],
      BN
    >;
    withdraw_assets_from_pool: InvokeFunction<
      [pool_asset: AssetIdInput, to: IdentityInput],
      void
    >;
  };
  constructor(id: string | Address, accountOrProvider: Account | Provider) {

    super(id, abi, accountOrProvider);
  }
}
